---
language: shell
cache:
  directories:
    - .brew
before_install:
  - make prepare brew_dir=$TRAVIS_BUILD_DIR/.brew
script:
  - make check brew_dir=$TRAVIS_BUILD_DIR/.brew
notifications:
  email: 8slashes+travis-ci@gmail.com
